@AstroBookings_HostAddress = http://localhost:5070

# Creates a valid rocket and verifies it is returned by the list endpoint.
POST {{AstroBookings_HostAddress}}/cohetes/
Content-Type: application/json
Accept: application/json

{
  "nombre": "Falcon",
  "alcance": "orbital",
  "capacidad": 4
}

###

GET {{AstroBookings_HostAddress}}/cohetes/
Accept: application/json

###

````````

# Response
